name: Android CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:

env:
  JAVA_VERSION: 18

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Setup JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: temurin
          cache: gradle
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew assembleRelease

  captureTest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Setup JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: temurin
          cache: gradle
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Capture with Roborazzi in dev branch
        run: ./gradlew recordRoborazziDebug

      - name: Checkout this branch
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Capture and Compare with Roborazzi
        run: ./gradlew compareRoborazziDebug

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot_result
          path: app/build/outputs/roborazzi

      - name: Check for UI differences
        id: check_ui_diff
        run: |
          if ls app/build/outputs/roborazzi/*compare* 1> /dev/null 2>&1; then
            echo "ui-diff-found=true" >> $GITHUB_OUTPUT
          else
            echo "ui-diff-found=false" >> $GITHUB_OUTPUT
          fi

      - name: Comment PR about UI differences
        if: ${{ steps.check_ui_diff.outputs.ui-diff-found == 'true' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            UI の差分あったよ！ :eyes:

      - name: Comment PR about no UI differences
        if: ${{ steps.check_ui_diff.outputs.ui-diff-found == 'false' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            UI の差分ないヨ！ :tada:


