name: Comment branch name

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  comment-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            This issue's work branch is "ZARDApp-${{github.event.issue.number}}".
