name: Visual Regression Testing

on:
  pull_request:
  label:
    types: [ created ]

env:
  JAVA_VERSION: 18

concurrency:
  group: vrt-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vrt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch for capture expected images
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Setup JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: temurin
          cache: gradle
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Capture with Roborazzi in dev branch
        run: ./gradlew recordRoborazziDebug
      - name: Copy expected image to .reg/expected
        run: mkdir -p .reg/expected; find app/build/outputs/roborazzi -type f ! -name '*.actual' ! -name '*.compare' -exec cp {} .reg/expected \;
      - name: show files in .reg/expected
        run: ls .reg/expected

      - name: Checkout this branch
        uses: actions/checkout@v4
        with:
          clean: false
      - name: Capture with Roborazzi in this branch
        run: ./gradlew recordRoborazziDebug
      - name: Copy actual image to directory_contains_actual_images directory
        run: mkdir -p directory_contains_actual_images; find app/build/outputs/roborazzi -type f ! -name '*.actual' ! -name '*.compare' -exec cp {} directory_contains_actual_images \;
      - name: show files in directory_contains_actual_images
        run: ls directory_contains_actual_images

      - name: npm install
        run: npm install
      - name: Set Environment Variables
        run: export AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} && export AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} && export AWS_REGION=ap-northeast-1
      - name: Use Node.js v20.11.1
        uses: actions/setup-node@v1
        with:
          node-version: "20.11.1"
      - name: npm install, build, and test
        run: |
          npm i
      - name: echo current branch
        run: echo ${GITHUB_REF#refs/heads/}
      - name: echo current branch
        run: echo ${GITHUB_HEAD_REF}
      - name: checkout test branch
        run: git checkout -b ${GITHUB_HEAD_REF#refs/heads/}
      - name: echo current branch
        run: git branch
#      - name: workaround for detached HEAD
#        run: |
#          git checkout ${GITHUB_HEAD_REF#refs/heads/} || git checkout -b ${GITHUB_HEAD_REF#refs/heads/} && git pull
      - name: run reg-suit
        run: |
          npx reg-suit run


