name: Visual Regression Testing

on:
  label:
    types: [ created ]

env:
  JAVA_VERSION: 18

concurrency:
  group: vrt-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vrt:
    if: ${{ github.event.label.name == 'VRT' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch for capture expected images
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Setup JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: temurin
          cache: gradle
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Capture with Roborazzi in dev branch
        run: ./gradlew recordRoborazziDebug
      - name: Copy expected image to .reg/expected
        run: mkdir -p .reg/expected; find app/build/outputs/roborazzi -type f ! -name '*.actual' ! -name '*.compare' -exec cp {} .reg/expected \;
      - name: show files in .reg/expected
        run: ls .reg/expected

      - name: Checkout this branch
        uses: actions/checkout@v4
        with:
          clean: false
      - name: Capture with Roborazzi in this branch
        run: ./gradlew recordRoborazziDebug
      - name: Copy actual image to directory_contains_actual_images directory
        run: mkdir -p directory_contains_actual_images; find app/build/outputs/roborazzi -type f ! -name '*.actual' ! -name '*.compare' -exec cp {} directory_contains_actual_images \;
      - name: show files in directory_contains_actual_images
        run: ls directory_contains_actual_images

      - name: npm install
        run: npm install
      - name: Create AWS Config File
        run: mkdir -p ~/.aws; echo "${{secrets.AWS_CONFIG}}" > ~/.aws/config
      - name: Create AWS Config File
        run: mkdir -p ~/.aws; echo "${{secrets.AWS_CREDENTIALS}}" > ~/.aws/credentials
      - name: Use Node.js v20.11.1
        uses: actions/setup-node@v1
        with:
          node-version: "20.11.1"
      - name: checkout test branch
        run: git checkout -b ${GITHUB_HEAD_REF#refs/heads/}
      - name: run reg-suit
        run: |
          npx reg-suit run


